export default {
  // 用户管理
  userAdd: 'sys:user:add',
  userUpdate: 'sys:user:update',
  userPwd: 'sys:user:pwd',
  userDelete: 'sys:user:delete',
  // 权限管理
  roleAdd: 'sys:role:add',
  roleUpdate: 'sys:role:update',
  roleDelete: 'sys:role:delete',
  // 菜单管理
  menuAdd: 'sys:menu:add',
  menuUpdate: 'sys:menu:update',
  menuDelete: 'sys:menu:delete',
  // 日志管理
  logsDelete: 'sys:logs:delete',
  logsShow: 'sys:logs:show',
  // 配置管理
  configAdd: 'sys:config:add',
  configUpdate: 'sys:config:update',
  configDelete: 'sys:config:delete',
  // 页面管理
  pagesShow: 'sys:pages:show',
  // 基本信息
  baseSave: 'love:base:save',
  // 相册管理
  photosAdd: 'love:photos:add',
  photosUpdate: 'love:photos:update',
  photosSort: 'love:photos:sort',
  photosDelete: 'love:photos:delete',
  // 留言管理
  messageDelete: 'love:message:delete',
  // 图片管理
  imageUpload: 'love:image:upload',
  imageDelete: 'love:image:delete',
  // 音乐管理
  musicUpload: 'love:music:upload',
  musicDelete: 'love:music:delete',
};
